sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/killingspree.wav
sound/misc/humiliation.wav
sound/misc/ultrakill.wav
sound/misc/headshot.wav
sound/misc/doublekill.wav
sound/misc/firstblood.wav
sound/misc/rampage.wav
sound/misc/unstoppable.wav
sound/misc/dominating.wav
sound/misc/perfect.wav
sound/misc/godlike.wav
sound/misc/prepare.wav
sound/misc/kenny1.wav
sound/misc/cracker1.wav
sound/misc/shot1.wav
sound/misc/revenge1.wav
sound/misc/doh.wav
sound/misc/nam1.wav
sound/misc/kickass1.wav
maps/de_train.res
